### ISSUE TITLE
Failed to connect: Native host has exited.

### ISSUE THREAD

**Issue by ar1a** [unremem/PoBTradeHelper#7]
Hi, trying to get the extension working. When I put the path in `C:\Users\aria\AppData\Roaming\Path of Building Community` and hit set pob path, it errors out with `Failed to connect: Native host has exited.`

Registry is all set up correctly: 
![image](https://github.com/unremem/PoBTradeHelper/assets/8436007/203aa2be-c242-490f-80cd-7ad0c2aec857)

Running the bat file seems to work fine:
![image](https://github.com/unremem/PoBTradeHelper/assets/8436007/154b1d9b-3e55-4df4-b996-638f24565d04)

I tried looking through the code but couldn't find a way to figure out why it's exiting. Do you have any advice?

**Comment by ar1a** [comment]
Seems like this is why

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aria\projects\pythtest\pob_wrapper\pob_wrapper\pob.py", line 108, in __init__
    raise ChildProcessError((stdin or '') + (stderr or ''))
ChildProcessError:
^0In 'OnFrame': Modules/DataLegionLookUpTableHelper.lua:287: Error occurred loading Glorious Vanity data
^8v2.37.0 master
^0Press Enter/Escape to dismiss, or F5 to restart the application.
stack traceback:
        [C]: in function 'error'
        ...rojects\pythtest\pob_wrapper\pob_wrapper\data\mockui.lua:233: in main chunk
        [C]: in function 'require'
        ...a\projects\pythtest\pob_wrapper\pob_wrapper\data\cli.lua:11: in main chunk
        [C]: at 0x004020f0```
